ibm_cloud_fail_over/__init__.py,sha256=tauGSfzSuiN178wixH7w2AK0vsIJ_s9v7bA8Xp_3OG4,149
ibm_cloud_fail_over/ibm_cloud_fail_over.py,sha256=B6zNVuUynNqfFyxg0g8dVXRkNdpruDlhcxXbtxR-IaU,21707
ibm_cloud_fail_over-0.0.5.dist-info/METADATA,sha256=nhD3kN_5Q6_Lc3_jUT1gXqNWpwjD49-cELGZ1I882C8,5282
ibm_cloud_fail_over-0.0.5.dist-info/WHEEL,sha256=qtCwoSJWgHk21S1Kb4ihdzI2rlJ1ZKaIurTj_ngOhyQ,87
ibm_cloud_fail_over-0.0.5.dist-info/licenses/LICENSE,sha256=xx0jnfkXJvxRnG63LTGOxlggYnIysveWIZ6H3PNdCrQ,11357
ibm_cloud_fail_over-0.0.5.dist-info/RECORD,,
